/**
 * The Surface seam.
 *
 * Everything above this interface (discovery agent, recorder, replay engine,
 * handoff) reasons in terms of screenshots, marked elements, locator bundles
 * and abstract actions. Everything below it (Playwright today, an OS
 * accessibility driver tomorrow) knows how to perceive and act on a concrete
 * surface. The artifact never references anything below this line.
 */
import type { ControlRole, Locator, LocatorStrategy } from '../schema/locator.js';

export interface MarkedElement {
  /** Number drawn on the screenshot; the model refers to elements by mark. */
  mark: number;
  role: ControlRole;
  /** Accessible name (best effort on legacy markup). */
  name: string;
  /** Frame name path the element lives in ("main", "top", ...). */
  frame: string;
  /** Viewport-relative bounding box in CSS px, main-frame coordinates. */
  bbox: { x: number; y: number; w: number; h: number };
  /** Current value for inputs/selects (masked for password fields). */
  value?: string;
  enabled: boolean;
  /** Candidate locator bundle generated by the surface for this element, most robust first. */
  locator: Locator;
}

export interface DialogEvent {
  type: string;
  message: string;
  /** What the surface did with it, per the active dialog policy. */
  response: 'accept' | 'dismiss';
  matchedRule?: string;
}

export interface Observation {
  at: string;
  screenshotPng: Buffer;
  viewport: { w: number; h: number };
  /** URL and title of the primary content frame (largest visible frame). */
  url: string;
  title: string;
  frames: { name: string; url: string; title: string }[];
  elements: MarkedElement[];
  /** Visible text of all frames, used by runtime-condition detectors. */
  text: string;
  /** Dialogs that fired since the previous observation. */
  dialogs: DialogEvent[];
  /** Last HTTP status seen for a document navigation, if any. */
  lastStatus?: number;
}

export type Target = { mark: number } | { locator: Locator } | { point: { x: number; y: number } };

export type SurfaceAction =
  | { type: 'navigate'; url: string }
  | { type: 'click'; target: Target }
  | { type: 'type'; target: Target; text: string; clear?: boolean; secret?: boolean }
  | { type: 'select'; target: Target; value: string }
  | { type: 'press'; key: string; target?: Target }
  | { type: 'wait'; ms: number };

export interface Resolved {
  /** Index into the locator's strategy bundle that resolved, and its kind. */
  index: number;
  kind: LocatorStrategy['kind'];
  frame: string;
  /** Text content of the resolved element (used by extract). */
  text: () => Promise<string>;
  bbox: () => Promise<{ x: number; y: number; w: number; h: number } | null>;
}

export interface DialogRule {
  /** Regex on the dialog message. */
  pattern: string;
  response: 'accept' | 'dismiss';
}

export interface Surface {
  readonly kind: 'web' | 'desktop';
  observe(opts?: { marks?: boolean }): Promise<Observation>;
  act(action: SurfaceAction): Promise<void>;
  /** Resolve a locator bundle to a live element. Returns null when no strategy matches. */
  resolve(locator: Locator): Promise<Resolved | null>;
  /** Visible text + current URL/title without a screenshot (cheap; used for polling checkpoints). */
  peek(opts?: { drainDialogs?: boolean }): Promise<{ url: string; title: string; text: string; dialogs: DialogEvent[]; lastStatus?: number }>;
  /** Native dialogs matching a rule get that response; anything else is dismissed and reported. */
  setDialogRules(rules: DialogRule[]): void;
  currentOrigin(): string;
  screenshot(): Promise<Buffer>;
  /** Rich evidence on failure. */
  saveTrace(path: string): Promise<void>;
  /** Handoff: start/stop capturing what a human does on the live session. */
  startHumanRecording(sink: (e: { kind: string; detail: string }) => void): Promise<void>;
  stopHumanRecording(): void;
  close(): Promise<void>;
}
